### ISSUE TITLE
I get an "Unknown command: 'NONE'", and I do not have a "NONE" command in my code

### ISSUE THREAD

**Issue by T9Air** [droans/klipper_extras#27]
### Description

When I try to run my Python script I get this error `// Unknown command: "NONE"`

### Reproduce

Add this gcode to a file: `LOG_FILE`

### Expected behavior

Everything works, I just get that error

### Extended Macro Config

```bash
functions:
    logger:
        path: /home/avraham/print_position_logger/logger.py
        function: increment_number
```

### Extended Template Config

```bash
[extended_template]
path: /home/avraham/print_position_logger/config.yaml
```

### Macro Config

```bash
[extended_macro LOG_FILE]
gcode:
    {logger("/home/avraham/print_position_logger/log.txt")}
```

### Macro Python Code

```python
def increment_number(filename):

  try:
    with open(filename, 'r+') as file:
      number = int(file.read() or 0)
      number += 1
      file.seek(0)
      file.truncate()
      file.write(str(number))
  except FileNotFoundError:
    with open(filename, 'w') as file:
      file.write('1')

```

### Klippy Venv Python

Python 3.X

### Installer Python

None

### Klippy Version

v1.0.0-130-gbd74334c

### Klippy Version

v0.3

### Additional Info

I am using this klipper version: https://github.com/0xD34D/klipper_ender3_v3_se/tree/e3v3se-display-support
@droans

**Comment by droans** [comment]
I'd need more logs if possible. Unfortunately, I'm not actively developing this anymore as I don't have the time and other repositories (such as DangerKlipper) are working on similar but better features.

Try using a different name for the function, it's possible that `logger` is a reserved keyword. If that doesn't work, try giving the Jinja function the same name as the Python function.
